#
# Makefile
# FabriceLuo, 2021-04-28 16:01
#
#

REPO      = autossh
DOWNLOAD_URL = https://api.github.com/repos/FabriceLuo/autossh/tarball/refs/tags/v0.1.0


include ../butterfly/makefile/download-install.mk

# vim:ft=make
#
