#
# Makefile
# fabriceluo, 2023-07-01 15:01
#

CLONE_URL = https://github.com/zsh-users/zsh-syntax-highlighting.git
CLONE_DST_ROOT = /home/fabrice/.oh-my-zsh/plugins
CLONE_DST_NAME = zsh-syntax-highlighting

include $(BUTTERFLY_DIR)/makefile/git-clone.mk

# vim:ft=make
#
