#
# Makefile
# fabriceluo, 2023-07-01 15:04
#

REPO 	= tree-sitter
BINARY_RELATIVE = 
DOWNLOAD_URL = https://github.com/tree-sitter/tree-sitter/releases/download/v0.25.3/tree-sitter-linux-x64.gz


include $(MAKEFILE_DIR)/download-install.mk

# vim:ft=make
#
