#
# Makefile
# fabriceluo, 2023-07-01 14:55
#

REPO 	= fzf
TAR_STRIP_COMPONENTS=0
BINARY_RELATIVE=
DOWNLOAD_URL = https://github.com/junegunn/fzf/releases/download/v0.61.3/fzf-0.61.3-linux_amd64.tar.gz

include $(MAKEFILE_DIR)/download-install.mk
# vim:ft=make
#
