#
# Makefile
# FabriceLuo, 2021-04-28 16:01
#
#
include ../../common/develop-debug.mk

REPO      = pet
DOWNLOAD_URL = https://github.com/knqyf263/pet/releases/download/v1.0.1/pet_1.0.1_linux_amd64.tar.gz

BINARY_RELATIVE =
TAR_STRIP_COMPONENTS = 0

include $(MAKEFILE_DIR)/download-install.mk

configure:



# vim:ft=make
#
