#
# Makefile
# FabriceLuo, 2021-04-28 16:01
#
#

OWNER     = universal-ctags
REPO      = ctags
REPO_TYPE = latest_tag

include $(MAKEFILE_DIR)/make-install.mk

configure:
	cd $(COMPILE_DIR) && /bin/sh ./autogen.sh && ./configure

# vim:ft=make
#
