#
# Makefile
# fabriceluo, 2023-07-02 01:55
#

REPO      = as-tree
DOWNLOAD_URL = https://github.com/jez/as-tree/archive/refs/heads/master.zip


include $(BUTTERFLY_DIR)/makefile/download-install.mk

# vim:ft=make
#
