#
# Makefile
# fabriceluo, 2021-09-17 22:15
#

REPO = cmake
BINARY_RELATIVE = bin
DOWNLOAD_URL = https://github.com/Kitware/CMake/releases/download/v3.31.7/cmake-3.31.7-linux-x86_64.tar.gz


include $(MAKEFILE_DIR)/download-install.mk


# vim:ft=make
#
