#
# Makefile
# FabriceLuo, 2021-04-28 16:01
#
#
include ../../common/develop-debug.mk

REPO      = pet
DOWNLOAD_URL = https://github.com/knqyf263/pet/releases/download/v0.4.0/pet_0.4.0_linux_amd64.tar.gz

BINARY_RELATIVE =
TAR_STRIP_COMPONENTS = 0

include $(BUTTERFLY_DIR)/makefile/download-install.mk

configure:



# vim:ft=make
#
