#
# Makefile
# fabriceluo, 2023-07-01 15:07
#

REPO 	= ripgrep
BINARY_RELATIVE = 
DOWNLOAD_URL = https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep-13.0.0-x86_64-unknown-linux-musl.tar.gz


include $(BUTTERFLY_DIR)/makefile/download-install.mk

# vim:ft=make
#
