#
# Makefile
# luominghao, 2021-04-29 12:06
#
#
OWNER     = tmux
REPO      = tmux
REPO_TYPE = latest_release

include ../butterfly/make-install.mk

finish:
	install -D -m 0600 ../butterfly/tmux/tmux.conf ~/.tmux.conf

# vim:ft=make
#
