#
# Makefile
# fabriceluo, 2023-07-01 15:01
#

CLONE_URL = https://github.com/romkatv/powerlevel10k.git
CLONE_DST_ROOT = /home/fabrice/.oh-my-zsh/themes
CLONE_DST_NAME = powerlevel10k

include $(BUTTERFLY_DIR)/makefile/git-clone.mk

# vim:ft=make
#
