#
# Makefile
# fabriceluo, 2023-07-01 15:04
#

REPO 	= stylua
BINARY_RELATIVE = 
DOWNLOAD_URL = https://github.com/JohnnyMorganz/StyLua/releases/download/v2.0.2/stylua-linux-x86_64.zip


include $(MAKEFILE_DIR)/download-install.mk

# vim:ft=make
#
