#
# Makefile
# fabriceluo, 2023-07-01 15:01
#

CLONE_URL = https://github.com/andresteingress/oh-my-zsh.git

CLONE_DST_ROOT = /home/fabrice
CLONE_DST_NAME = .oh-my-zsh

include $(BUTTERFLY_DIR)/makefile/git-clone.mk

# vim:ft=make
#
