#
# Makefile
# fabriceluo, 2023-07-01 14:55
#

REPO 	= bat
BINARY_RELATIVE =
DOWNLOAD_URL = https://github.com/sharkdp/bat/releases/download/v0.23.0/bat-v0.23.0-x86_64-unknown-linux-musl.tar.gz

include $(BUTTERFLY_DIR)/makefile/download-install.mk
# vim:ft=make
#
