#
# Makefile
# fabriceluo, 2023-07-01 14:59
#

REPO 	= delta
DOWNLOAD_URL = https://github.com/dandavison/delta/releases/download/0.16.5/delta-0.16.5-x86_64-unknown-linux-musl.tar.gz

include $(BUTTERFLY_DIR)/makefile/download-install.mk
# vim:ft=make
#
