#
# Makefile
# fabriceluo, 2023-07-01 15:04
#

REPO 	= fd
BINARY_RELATIVE = 
DOWNLOAD_URL = https://github.com/sharkdp/fd/releases/download/v10.2.0/fd-v10.2.0-x86_64-unknown-linux-musl.tar.gz


include $(MAKEFILE_DIR)/download-install.mk

# vim:ft=make
#
