#
# Makefile
# luominghao, 2020-09-02 08:23
#

SUBDIRS = fzf yadm tmux ctags golang cmake autossh pet bat delta fd oh-my-zsh powerlevel10k ripgrep tmux-tpm zsh-autosuggestions zsh-syntax-highlighting

include $(MAKEFILE_DIR)/make-subdirs.mk

# vim:ft=make
#
