#
# Makefile
# fabriceluo, 2021-09-17 22:15
#

REPO = go
BINARY_RELATIVE = bin
DOWNLOAD_URL = https://golang.org/dl/go1.17.linux-amd64.tar.gz


include ../butterfly/makefile/download-install.mk


# vim:ft=make
#
