#
# Makefile
# fabriceluo, 2021-09-17 22:15
#

REPO = go
BINARY_RELATIVE = bin
DOWNLOAD_URL = https://golang.google.cn/dl/go1.21.0.linux-amd64.tar.gz


include $(BUTTERFLY_DIR)/makefile/download-install.mk


# vim:ft=make
#
