#
# Makefile
# fabriceluo, 2023-07-01 15:04
#

REPO 	= nvim
DOWNLOAD_URL = https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz


include $(BUTTERFLY_DIR)/makefile/download-install.mk

# vim:ft=make
#
