#
# Makefile
# fabriceluo, 2023-07-01 15:19
#

REPO 	= yq
DOWNLOAD_URL = https://github.com/mikefarah/yq/releases/download/v4.34.1/yq_linux_amd64.tar.gz

include $(BUTTERFLY_DIR)/makefile/download-install.mk

# vim:ft=make
#
