#
# Makefile
# fabriceluo, 2023-07-01 15:07
#

REPO 	= ripgrep
BINARY_RELATIVE = 
DOWNLOAD_URL = https://github.com/BurntSushi/ripgrep/releases/download/14.1.1/ripgrep-14.1.1-x86_64-unknown-linux-musl.tar.gz


include $(MAKEFILE_DIR)/download-install.mk

# vim:ft=make
#
