#
# Makefile
# fabriceluo, 2023-07-01 14:59
#

REPO 	= delta
BINARY_RELATIVE = 
DOWNLOAD_URL = https://github.com/dandavison/delta/releases/download/0.18.2/delta-0.18.2-x86_64-unknown-linux-musl.tar.gz

include $(MAKEFILE_DIR)/download-install.mk
# vim:ft=make
#
