#
# Makefile
# fabriceluo, 2023-07-01 15:04
#

REPO 	= nvim
DOWNLOAD_URL = https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz


include $(MAKEFILE_DIR)/download-install.mk

configure:
	#@su -c 'source /home/fabrice/.pathrc && nvim --headless +"lua require('lazy').sync({ wait = true })" +"MasonToolsUpdateSync" +qa' fabrice

# vim:ft=make
#
